events {}

http {
  upstream backendservers {
    server backend1:8090;
    server backend2:8090;
  }

  server {
    listen 8090;

    location / {
      proxy_pass http://backendservers;
      proxy_set_header Host localhost;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}