events {}

http {
  server {
    listen 80;

    location / {
      proxy_pass http://frontend-lb:80;
    }

    location /api/ {
      proxy_pass http://backend-lb:8090/;
    }

    location /auth/ {
      proxy_pass http://keycloak:9090/;

      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto http;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}